### ISSUE TITLE
[Bug]: Some builtin-extensions rely on launch module that has deprecated dependencies (flowdas-meta)

### ISSUE THREAD

**Issue by Th3Rom3** [lllyasviel/stable-diffusion-webui-forge#514]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

General functions of the webui work without a problem but the installation routines of some of the builtin extensions (forge_legacy_preprocessor; sd_forge_controlnet) which are called by launch.py are not executed correctly due to a missing launch python module which relies on deprecated dependencies.

### Steps to reproduce the problem

Clone repository and run via python launch.py

### What should have happened?

Setup of integrated extensions should have completed gracefully.

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome, Other

### Sysinfo

[sysinfo-2024-03-08-16-10.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14540458/sysinfo-2024-03-08-16-10.json)

### Console logs

```Shell
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
Version: f0.0.17v1.8.0rc-latest-274-ge48533bd
Commit hash: e48533bdcd08118c5cd7e2c1de14c91c3b7fc8ec
*** Error running install.py for extension /media/scratch/StableDiffusion/Forge/stable-diffusion-webui-forge/extensions-builtin/forge_legacy_preprocessors.
*** Command: "/media/scratch/Python-envs/A1111/bin/python" "/media/scratch/StableDiffusion/Forge/stable-diffusion-webui-forge/extensions-builtin/forge_legacy_preprocessors/install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "/media/scratch/StableDiffusion/Forge/stable-diffusion-webui-forge/extensions-builtin/forge_legacy_preprocessors/install.py", line 1, in <module>
***     import launch
*** ModuleNotFoundError: No module named 'launch'
*** Error running install.py for extension /media/scratch/StableDiffusion/Forge/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet.
*** Command: "/media/scratch/Python-envs/A1111/bin/python" "/media/scratch/StableDiffusion/Forge/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "/media/scratch/StableDiffusion/Forge/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/install.py", line 1, in <module>
***     import launch
*** ModuleNotFoundError: No module named 'launch'
Launching Web UI with arguments: --disable-attention-upcast --ckpt-dir /media/scratch/StableDiffusion/ComfyUI/models/checkpoints --vae-dir /media/scratch/StableDiffusion/ComfyUI/models/vae --lora-dir /media/scratch/StableDiffusion/ComfyUI/models/loras --embeddings-dir /media/scratch/StableDiffusion/ComfyUI/models/embeddings
Total VRAM 16368 MB, total RAM 31986 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6800 : native
VAE dtype: torch.float32
CUDA Stream Activated:  False
disabling upcasting of attention
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --attention-split
ControlNet preprocessor location: /media/scratch/StableDiffusion/Forge/stable-diffusion-webui-forge/models/ControlNetPreprocessor
Loading weights [8f1e00a754] from /media/scratch/StableDiffusion/ComfyUI/models/checkpoints/SDXL_Artium_v10.safetensors
2024-03-08 17:09:21,535 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860
```

### Additional information

The dependencies of the mentioned `launch` module `flowdas-meta` are no longer available via the normal means (https://libraries.io/pypi/flowdas-meta). As such installation of the launch module is no longer possible without manually manipulating the dependencies.

**Comment by Th3Rom3** [comment]
I have tested a variety of configurations and I figured that this problem only occurs when running the webui by invoking launch.py via an absolute path. Running it from within the forge folder seems to mitigate the problem.

I assume this is probably enough to know and the issue can be closed but I wanted to leave it up for a few days and to keep the information available to posterity.

Will close in 7 days unless this issue gets further feedback.
